### PR TITLE
attempt to reconnect upon JSON parse errors

### PR DESCRIPTION
**Pull request by ericdagenais**
For example, API returns HTML during maintenance mode

### CODE REVIEW

**Comment by ianfisk** [comment]
@DVLP are there any plans to merge this? I am experiencing a parse error when developing a PWA trying to connect offline, and it appears there is no good way to get notified of or catch the error.

**Comment by DVLP** [comment]
@ianfisk done

**Comment by ianfisk** [comment]
Thanks @DVLP!

**Comment by ianfisk** [comment]
When do you expect to publish this in a new version?

**Comment by ianfisk** [comment]
BTW this is a really awesome package!

**Pull request merged**
