### PR TITLE
Upgrade to SignalR 2.4.1

### PR DESCRIPTION
**Pull request by erzki**
To use a hosted Azure SignalR Service we need SignalR version 2.4.x.

This PR solves that.

### CODE REVIEW

**Comment by malteA** [comment]
I tried using your branch as a local npm package, with azure SignalR service.
Maybe Im using it the wrong way for some reason I allways get status code 429 `Connection count reaches limit.` and i tried connecting only with 1 client, 1 server and 1 hub so i shouldnt run into the free trier limit with azure.

**Comment by erzki** [comment]
Hi

I have the same problem, but I can't see that it's because of my code.

/Erik

Den fre 17 apr. 2020 kl 15:29 skrev Malte <notifications@github.com>:

**Comment by malteA** [comment]
Hi Erik,

your code seems to be fine, i fiddled around a lot and managed to get it working.
I didnt need to change anything in your code.

In my Startup.cs i had to set the `ConnectionCount = 1` afterwards it just worked.

```c#
app.MapAzureSignalR(this.GetType().FullName, new HubConfiguration(), options => options.ConnectionCount = 1);
```

Malte

**Comment by erzki** [comment]
Great that you found out about ConnectionCount. 
We are paying for the Azure Service anyway so I didn't spend time on that.

How do we proceed with this PR?

**Comment by DVLP** [comment]
thanks for your contributions! are there any breaking changes here?

**Comment by erzki** [comment]
It should not be any breaking changes by updating signalR javacsript version from v2.2.1 to 2.4.1.

We have tested it in our code base and it worked without changing any code.

It would be nice if someone else can try it aswell.

**Comment by gregveres** [comment]
@erzki @DVLP I will try it on my code code and get back to you. If Erik's code works, then I will be happy to use his PR instead of my PR.

In my PR, I have incorporated some changes to the readme file to update how to use this with typescript. I don't care if you don't take those changes since I already know how to use it with typescript now. I just need the official package to be upgraded to use the newest version of signalr.

**Comment by gregveres** [comment]
@erzki @DVLP It seems to work fine. I would appreciate it being merged and a new NPM version created. 

I would also recommend you take the readme from my PR

**Comment by erzki** [comment]
@gregveres I copied your Readme file now into this PR (#51). Also added text that it works together with a hosted Azure SignalR Service.

**Comment by gregveres** [comment]
Ok. I will see how I can retract my PR so that it isn't confusing.

**Comment by cmonteiro128** [comment]
@DVLP @erzki Can we get this merged?

**Comment by alaaan** [comment]
Would love to see this merged

**Comment by erzki** [comment]
I would like to get it merged but I don't have permissions. Should I create a new package?

**Comment by cmonteiro128** [comment]
@erzki I would unless @DVLP responds soon

**Comment by alaaan** [comment]
@erzki hook up a new package! :)

**Comment by erzki** [comment]
Hi! Back after summer vacation.

What do you think the package should be named?

**Comment by cmonteiro128** [comment]
> Hi! Back after summer vacation.
> 
> What do you think the package should be named?

Be creative :)

**Comment by alaaan** [comment]
> Hi! Back after summer vacation.
> 
> What do you think the package should be named?

Follow your heart!

**Comment by gregveres** [comment]
honestly I would name it signalr-no-jquery2 so that when people search for signalr jquery they find it.

**Comment by erzki** [comment]
Please try it https://www.npmjs.com/package/signalr-asp-net

**Comment by e965** [comment]
Because @erzki disappeared somewhere, I made my own fork from the project with some improvements (and with the updated SignalR, of course).

enjoy https://github.com/cojamru/signalr-no-jquery

**Comment by DVLP** [comment]
Looks like I neglected this package for too long but I merged the PR and published in NPM too. As you can see I'm not too involved in this project anymore due to being at 100% capacity. I made this package on one contract job, a few years ago in a legacy system for my and my team's convenience and never thought it will be very useful in the future due to even at its creation time ASP Core already being available.

**Pull request merged**
